export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_ALERT = "CHANGE_ALERT";
export const CHANGE_LOADING = "CHANGE_LOADING";
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const ME_SUCCESS = "ME_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"